---
services:
  node:
    image: ihkmuenchen/openethereum:alpine
    platform: linux/amd64
    container_name: leopold_node
    restart: unless-stopped
    command: "--config /home/parity/authority.toml"
    volumes:
      - "${PWD}/dist/staging/authority.toml:/home/parity/authority.toml:ro"
      - "${PWD}/dist/staging/reserved_peers:/home/parity/chain/reserved_peers:ro"
      - "${PWD}/dist/staging/spec.json:/home/parity/chain/spec.json:ro"
      - "${PWD}/dist/staging/password:/home/parity/password:ro"
      - "${PWD}/dist/staging/leopold:/home/parity/data/keys/leopold"
      - "${PWD}/dist/staging/key.priv:/home/parity/data/network/key/"
      - "${PWD}/dist/staging/data:/home/parity/data"
    ports:
      - target: 8545
        published: 8545
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host

  leopold-metrics-guest:
    image: ihkmuenchen/cbc-metrics:latest
    container_name: leopold_metrics
    restart: unless-stopped
    ports:
      - "3008:3008"
    environment:
      APPLICATION_WEB3_URL: http://node:8545
      APPLICATION_WEB3_CLIENT: "OpenEth"
      APPLICATION_ALIASES_ADDRESS: 0x261E48Fb768C50B950c18A5cEdBd0Ab2Bedaf5eB
      APPLICATION_ALIASES_ENABLED: "true"
      SERVER_PORT: 3008
      SPRING_ZIPKIN_ENABLED: "false"
      LOGGING_LEVEL_DE_IHK_MUENCHEN_CONTROL: "INFO"
      APPLICATION_SCHEDULER_INITIALDELAYALIAS: "3000"
      APPLICATION_SCHEDULER_FIXEDDELAYALIAS: "3000"
      APPLICATION_QUOTA_BYTES: 2147483648  # 2048 * 1024 * 1024
